Repository ArkEcosystem/javascript-cli, pull requests merged in 2019-05, with the labels that each got.

#114 fix: CircleCI missing deps
  .circleci/config.yml
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#113 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved

#110 Update README.md
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved

#119 chore: use organization-wide GitHub Configuration
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Low, Type: Task
